\documentclass[a4paper]{article}
\usepackage{titling}
\usepackage{authblk}
\usepackage{fancyhdr}
\usepackage[hyphens]{url}
\usepackage{hyperref}
\usepackage{rsc}
\usepackage{siunitx}
\usepackage{graphicx}
\usepackage{mhchem}
\usepackage{amsmath}
\usepackage{listings}
\usepackage{color}
\usepackage[htt]{hyphenat}

\definecolor{dkgreen}{rgb}{0,0.6,0}
\definecolor{gray}{rgb}{0.5,0.5,0.5}
\definecolor{mauve}{rgb}{0.58,0,0.82}

\lstset{frame=tb,
  language=Python,
  aboveskip=3mm,
  belowskip=3mm,
  showstringspaces=false,
  columns=flexible,
  basicstyle={\ttfamily},
  numbers=none,
  numberstyle=\tiny\color{gray},
  keywordstyle=\color{blue},
  commentstyle=\color{dkgreen},
  stringstyle=\color{mauve},
  breaklines=true,
  breakatwhitespace=true,
  tabsize=3,
  postbreak=\mbox{\textcolor{red}{$\hookrightarrow$}\space}
}
\DeclareSIUnit\Fahrenheit{\degree F}

\title{Lecture 4: Debugging}
\author[1]{Dr Benjamin J. Morgan}
\author[1,2]{Dr Andrew R. McCluskey}
\affil[1]{Department of Chemistry, University of Bath, email: b.j.morgan@bath.ac.uk}
\affil[2]{Diamond Light Source, email: andrew.mccluskey@diamond.ac.uk}
\setcounter{Maxaffil}{0}
\renewcommand\Affilfont{\itshape\small}

\pagestyle{fancy}
\fancyhf{}
\rhead{CH40208}
\lhead{\thetitle}
\rfoot{\thepage}

\begin{document}
\maketitle

\section*{Aim}
This lecture will introduce \emph{debugging} skills and suggest methods to improve your ability to overcome errors in your code.

\section{Error messages}
Human beings are fallible, therefore code will have bugs.
However, there are some tips that we can use to deal with the bugs in our code and make them less of a nuesence.

One of the most powerful tools that is available to us is the quality of the code and libraries that are written in Python.
For example, if you \texttt{import} the square-root (\texttt{sqrt}) function from the basic Python library \texttt{math} and give it a list as an argument,
\begin{lstlisting}
from math import sqrt

a = [0, 1, 2, 3]

print(sqrt(a))
\end{lstlisting}
This will lead to an error.
However, this error will come with a \emph{traceback} showing where the error came from and will give some information, at the bottom, about why the error occurred.
You should get an error that looks like this,
\begin{lstlisting}
TypeError                                 Traceback (most recent call last)
<ipython-input-14-29539b5bdc2d> in <module>
----> 1 print(sqrt(a))

TypeError: must be real number, not list
\end{lstlisting}
As we can see, the error that has been thrown is a \texttt{TypeError}, and we are given the additional information about the error that: \texttt{must be real number, not list}.
We can use this to parse the root cause of the problem, a \texttt{TypeError} indicates that \emph{something} is of the wrong \emph{type}, and we are told that this \emph{something} should be a \texttt{real number} and not a \texttt{list}.
It is clear that the arugment being passed to the \texttt{sqrt()} function is of \emph{type} \texttt{list}, and therefore this is the problem.\footnote{Note that the \texttt{sqrt} function from the \texttt{math} library can only take single values and return the square-root. This NumPy \texttt{np.sqrt()} function can however handle objects of type \texttt{list} and NumPy arrays.}
\begin{table}[h]
	\centering
	\caption{Some error types that exist in Python.}
	\label{tab:ops}
	\begin{tabular}{c p{0.6\textwidth}}
		\hline
		Error & Context \\
		\hline
		\texttt{IndexError} & Trying to access an invalid index \\
		\texttt{ModuleNotFoundError} & Trying to import a non-existent module \\
		\texttt{TypeError} & Performing an action on an inappropriate type \\
		\texttt{ValueError} & Function argument is an inappropriate type \\
		\texttt{NameError} & Object with given variable name could not be found \\
		\texttt{ZeroDivisionError} & Trying to divide something by zero \\
		\hline
	\end{tabular}
\end{table}

\vspace{\baselineskip}
\begin{center}
	\noindent\fbox{%
	    \begin{minipage}{0.9\textwidth}%
	        \vspace{0.15\baselineskip}
			\subsubsection*{Exercise}
	        Try and determine the cause of the error messages thrown by the following commands (where a semi-colon indicated a new line):
          \begin{itemize}
            \item{\texttt{a = [0, 1, 2, 3]; np.square(a[-5])}}
            \item{\texttt{np.power(2)}}
            \item{\texttt{mp.array([1, 1, 2, 3, 5, 8, 13])}}
          \end{itemize}
          If you are not sure what a particular function does search for ``numpy'' and then the function name online, e.g. ``numpy power''.
	    \end{minipage}
	}
\end{center}

The majority of Python libraries will have helpful error messages such as the one given above (especially commonly used packages such as NumPy, pandas and matplotlib).
However, sometimes it is not immediately clear what the error message means, for this it is often necessary to leverage the most important tool in a programmers arsenal -- the internet.
Consider the following example, we have an array containing the numbers 1 to 9, which we reshape into a \texttt{(3, 3)} array and want to obtain the mean of each of the rows (where columns are the first axis and rows the second),
\begin{lstlisting}
import numpy as np

a = np.linspace(1, 9, 9)
a = np.reshape(a, (3, 3))

print(a)

print(np.mean(a, axis=2))
\end{lstlisting}
After running the above code, we will get the following error traceback,
\begin{lstlisting}
IndexError                                Traceback (most recent call last)
<ipython-input-16-d032bc661941> in <module>
----> 1 np.mean(a, axis=2)

~/python3.6/site-packages/numpy/core/fromnumeric.py in mean(a, axis, dtype, out, keepdims)
   3116
   3117     return _methods._mean(a, axis=axis, dtype=dtype,
-> 3118                           out=out, **kwargs)
   3119
   3120

~/python3.6/site-packages/numpy/core/_methods.py in _mean(a, axis, dtype, out, keepdims)
     60
     61     is_float16_result = False
---> 62     rcount = _count_reduce_items(arr, axis)
     63     # Make this warning show up first
     64     if rcount == 0:

~/python3.6/site-packages/numpy/core/_methods.py in _count_reduce_items(arr, axis)
     53     items = 1
     54     for ax in axis:
---> 55         items *= arr.shape[ax]
     56     return items
     57

IndexError: tuple index out of range
\end{lstlisting}
There is a lot of information here, but we want to focus on just the last line, which reads \texttt{IndexError: tuple index out of range}, which is rather opaque.
This is where the internet is our friend, if you \emph{copy and paste} this final line into Google\footnote{Or any decent search engine.}, you will likely find a lot of hits from a website called \textbf{Stack Overflow}.
Stack Overflow is a message board style website where people can post programming (and mathematics and general computation) questions and others will answer.
One of the great things about this website is that it is popular, so nearly all of the questions you could ask have already been answered.
%
\begin{figure}[t]
\centering
\includegraphics[width=0.8\textwidth]{wisdom_of_the_ancients}
\label{fig:wisdow}
\caption{Of course not every question will have an answer. Taken from xkcd (\url{https://xkcd.com/979/}).}
\end{figure}
%

If we put the error message from the above example into our search engine, we should be able to get some useful Stack Overflow answers.
For example\footnote{https://stackoverflow.com/questions/20296188/indexerror-tuple-index-out-of-range-python}, one of the answers suggests \emph{``I suspect you mean to say [0] where you say [1] and [1] where you say [2]. Indexes are 0-based in Python.''}, which can immediately lead us to our bug.
In the line \texttt{print(np.mean(a, axis=2))}, we assigned the row axis to the value $2$, however Python counts from $0$, to the column axis should be $0$, making the row axis $1$.
If we run the above code again with \texttt{axis=1}, we should get the following returned,
\begin{lstlisting}
[2. 5. 8.]
\end{lstlisting}
It may sound like a rather simple approach to debugging, however, the popularity of Python and the clarity of the error messages mean that \emph{Googling} the problem is often on of the quickest ways to debug a complex issue.

A final note on error messages is one of warning.
The nature of Python error messages are as \emph{tracebacks}, this means that the error traces back through the different levels of the library/code and then prints the cause of the error.
This means that Python error messages can be \textbf{very} long, take the code below (which makes use of the popular plotting library matplotlib) as an example,
\begin{lstlisting}
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(1, 10, 10)
y = np.linspace(1, 10, 9)

plt.plot(x, y)
plt.show()
\end{lstlisting}
Running this code will produce an error message that is more than 40 lines long and can be rather worrying the first time that you encounter it.
However, it is important not to worry about the size of the error message, but simply to scroll to the bottom of the page and to find the real reason for the error being thrown.
In the above example the error that is relevant is \texttt{ValueError: x and y must have same first dimension, but have shapes (10,) and (9,)}, which is relatively straight forward to parse.
One of the things we are plotting is an array of 10 numbers, while the other is an array of 9 (and therefore it doesn't make sense to plot them together).

\section{Raising your own Errors}
In your own functions, it is possible \emph{raise} your own errors using the following syntax, 
\begin{lstlisting}
# Raising errors

def celsius_to_kelvin(celsius):
    """
    convert from Celsius to Kelvin
    """
    if celsius < -273.15:
        raise ValueError('The temperature was less than '
                         '-273.15 and would produe an '
                         'unphysical temperature of '
                         'less than 0 K')
    else:
        return celsius + 273.15
\end{lstlisting}
Any of the error type that are outlined in Table~\ref{tab:ops} may be used in the same way as \texttt{ValueError()} is used in the example above.
The string that is passed to the \texttt{ValueError()} function will be printed to the screen such that the user can better understand the cause of the error. 

\section{Problem}
This week we will look at the rotation of a molecule on a surface (such that the $z$ coordinate does not change), for example a water molecule on the surface of some crystal. 
The ability to rotate a molecule in space is extremely important in computational chemistry, for example in drug discovery a ligand molecule may be rotated with a binding pocket of a protein molecule in order to evaulate the lowest energy interaction and offering insight into ligand design as a result. 
To help with visualisation of the molecule on a surface, we have provided a \textbf{module} on Moodle (\texttt{visualisation.py}) that uses the \texttt{matplotlib} library to enable visual inspection of the molecule on a surface.

First, you must read in the file given on moodle (\texttt{water.txt}) using \texttt{np.loadtxt}, then by passing the \texttt{x} and \texttt{y} arrays to the \texttt{visualisation.show(x, y)} function to produce the visualisation. 
We now turn our focus to the rotation of a molecule (around the origin), Figure~\ref{fig:rotation} shows a graphical description of the transformation required to rotate a point from $(x, y)$ through $\beta$ around the origin to $(x', y')$.
%
\begin{figure}[t]
  \centering
  \includegraphics[width=0.5\textwidth]{rotation}
  \caption{\label{fig:rotation} A graphical description of the mathematics underlying the rotation transformation.}
\end{figure}
%

It is shown in Figure~\ref{fig:rotation} that the position of $x$ and $y$ may be described by basic trigonometry as, 
%
\begin{equation}
  \begin{aligned}
    x & = r \cos{\alpha}, \\
    y & = r \sin{\alpha}.
  \end{aligned}
\label{equ:xy}
\end{equation}
%
While the position of $x'$ and $y'$ can be described as,
%
\begin{equation}
  \begin{aligned}
    x' & = r \cos{(\alpha + \beta)}, \\
    y' & = r \sin{(\alpha + \beta)}.
  \end{aligned}
\end{equation}
%
Trigonometric identities (which can be found online \url{http://en.wikipedia.org/wiki/List_of_trigonometric_identities#Angle_sum_and_difference_identities}) may then be used to evaluate $x'$ and $y'$ as follows, 
%
\begin{equation}
  \begin{aligned}
    x' & = r \cos{\alpha}\cos{\beta} - r\sin{\alpha}\sin{\beta}, \\
    y' & = r \sin{\alpha}\cos{\beta} - r\cos{\alpha}\sin{\beta}.
  \end{aligned}
\label{equ:trig}
\end{equation}
%
Finally, by replacing elements of Equation~\ref{equ:trig} with those from Equation~\ref{equ:xy} we may obtain straight-forward transformations that lead from $(x, y)$ to $(x', y')$, 
%
\begin{equation}
  \begin{aligned}
    x' & = x\cos{\beta} - y\sin{\beta}, \\
    y' & = y\cos{\beta} - x\sin{\beta}.
  \end{aligned}
\label{equ:final}
\end{equation}
%

Using the transformations outlined in Equation~\ref{equ:final}, you now must create a module named \texttt{transform} that includes a function called \texttt{rotation} that will take three variables \texttt{x}, \texttt{y}, and \texttt{angle}.
This function will perform a rotation of \texttt{angle} on \texttt{x} and \texttt{y} to produce \texttt{x\_new} and \texttt{y\_new}, which are returned from the function. 
Use the \texttt{visualisation.show} function to observe the rotation of the water molecule. 

%\bibliographystyle{rsc}
%\bibliography{handout_4}

\end{document}
